/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.health.hospital;

import java.awt.Cursor;
import java.awt.Image;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.GroupLayout;
import javax.swing.JLabel;
import javax.swing.JPanel;


/**
 *
 * @author chinex
 */
public class LoginFrame extends javax.swing.JFrame {

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();
        timerhomePanel.setVisible(true);
        errorLabel.setVisible(false);
        backgroundPanel.setVisible(true);
        patOptionPanell.setVisible(false);
        mainPanel.setVisible(true);
        parentpanel.setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        mainPanel = new javax.swing.JPanel();
        subPanel = new javax.swing.JPanel();
        usernamePanel = new javax.swing.JPanel();
        username = new javax.swing.JLabel();
        passwordPanel = new javax.swing.JPanel();
        password1 = new javax.swing.JLabel();
        loginButton = new javax.swing.JButton();
        signup = new javax.swing.JLabel();
        PasswordField = new javax.swing.JPasswordField();
        errorLabel = new javax.swing.JLabel();
        urAccount = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        companylabel = new javax.swing.JLabel();
        imageLabel = new javax.swing.JLabel();
        MAINFRAMEIMAGELabel = new javax.swing.JLabel();
        parentpanel = new javax.swing.JPanel();
        homesep = new javax.swing.JSeparator();
        HomeLabel = new javax.swing.JLabel();
        DiagnosisLabel = new javax.swing.JLabel();
        patientRegistration = new javax.swing.JLabel();
        accountLabel = new javax.swing.JLabel();
        patSep = new javax.swing.JSeparator();
        allpatsep = new javax.swing.JSeparator();
        homeSep = new javax.swing.JSeparator();
        secregsep = new javax.swing.JSeparator();
        timerhomePanel = new javax.swing.JPanel();
        backgroundPanel = new javax.swing.JPanel();
        patOptionPanell = new javax.swing.JPanel();
        patOptionpanel2 = new javax.swing.JPanel();
        RadioFAMILY = new javax.swing.JRadioButton();
        RadioPersonal = new javax.swing.JRadioButton();
        RadioHMO = new javax.swing.JRadioButton();
        RadioPostNatal = new javax.swing.JRadioButton();
        patOptionRegProceedButton = new javax.swing.JButton();
        patOptionPanelerrorLabel = new javax.swing.JLabel();
        HomePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        TimeLabel = new javax.swing.JLabel();
        patOptionPanelwelcomeLabelLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BEUHIER HOSPITAL MANAGEMENT SYSTEM");
        setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        setIconImages(null);

        mainPanel.setBackground(new java.awt.Color(102, 153, 255));

        subPanel.setBackground(new java.awt.Color(204, 204, 255));
        subPanel.setForeground(new java.awt.Color(153, 153, 255));

        usernamePanel.setBackground(new java.awt.Color(204, 204, 204));

        username.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        username.setText("USERNAME");

        javax.swing.GroupLayout usernamePanelLayout = new javax.swing.GroupLayout(usernamePanel);
        usernamePanel.setLayout(usernamePanelLayout);
        usernamePanelLayout.setHorizontalGroup(
            usernamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usernamePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(username)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        usernamePanelLayout.setVerticalGroup(
            usernamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usernamePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        passwordPanel.setBackground(new java.awt.Color(204, 204, 204));

        password1.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        password1.setText("PASSWORD");

        javax.swing.GroupLayout passwordPanelLayout = new javax.swing.GroupLayout(passwordPanel);
        passwordPanel.setLayout(passwordPanelLayout);
        passwordPanelLayout.setHorizontalGroup(
            passwordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(passwordPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(password1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        passwordPanelLayout.setVerticalGroup(
            passwordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, passwordPanelLayout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addComponent(password1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        loginButton.setBackground(new java.awt.Color(153, 153, 153));
        loginButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        loginButton.setForeground(new java.awt.Color(102, 153, 255));
        loginButton.setText("LOGIN");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        signup.setBackground(new java.awt.Color(102, 102, 102));
        signup.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        signup.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        signup.setText("Sign Up");
        signup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signupMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                signupMouseEntered(evt);
            }
        });

        PasswordField.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N

        errorLabel.setFont(new java.awt.Font("Bell MT", 1, 15)); // NOI18N
        errorLabel.setText("error");

        urAccount.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        urAccount.setForeground(new java.awt.Color(102, 102, 255));
        urAccount.setText("Login To Your Account");

        usernameField.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N

        javax.swing.GroupLayout subPanelLayout = new javax.swing.GroupLayout(subPanel);
        subPanel.setLayout(subPanelLayout);
        subPanelLayout.setHorizontalGroup(
            subPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(usernamePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(passwordPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(subPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(subPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, subPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(urAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(subPanelLayout.createSequentialGroup()
                        .addComponent(signup, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(subPanelLayout.createSequentialGroup()
                        .addGroup(subPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 36, Short.MAX_VALUE))
                    .addComponent(errorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        subPanelLayout.setVerticalGroup(
            subPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subPanelLayout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(urAccount)
                .addGap(31, 31, 31)
                .addComponent(usernamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(passwordPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(errorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(loginButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addComponent(signup)
                .addGap(25, 25, 25))
        );

        companylabel.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        companylabel.setForeground(new java.awt.Color(102, 102, 102));
        companylabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        companylabel.setText("BEUHIER RALPH HOSPITAL");

        imageLabel.setBackground(new java.awt.Color(153, 204, 255));
        imageLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\chinex\\Documents\\NetBeansProjects\\hospitalmanagementsystem\\logo.png")); // NOI18N

        MAINFRAMEIMAGELabel.setForeground(new java.awt.Color(102, 102, 102));
        MAINFRAMEIMAGELabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\chinex\\Documents\\NetBeansProjects\\hospitalmanagementsystem\\hospitallogo2.png")); // NOI18N

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MAINFRAMEIMAGELabel, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(companylabel, javax.swing.GroupLayout.PREFERRED_SIZE, 673, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(subPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(subPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addComponent(companylabel, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(imageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(MAINFRAMEIMAGELabel, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        parentpanel.setBackground(new java.awt.Color(0, 153, 255));

        HomeLabel.setFont(new java.awt.Font("Bell MT", 1, 30)); // NOI18N
        HomeLabel.setForeground(new java.awt.Color(255, 255, 255));
        HomeLabel.setText("Home");
        HomeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ControlLabelMouseEntered(evt);
            }
        });

        DiagnosisLabel.setFont(new java.awt.Font("Bell MT", 1, 30)); // NOI18N
        DiagnosisLabel.setForeground(new java.awt.Color(255, 255, 255));
        DiagnosisLabel.setText("Diagnosis");
        DiagnosisLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DiagnosisLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ControlLabelMouseEntered(evt);
            }
        });

        patientRegistration.setFont(new java.awt.Font("Bell MT", 1, 30)); // NOI18N
        patientRegistration.setForeground(new java.awt.Color(255, 255, 255));
        patientRegistration.setText("Patient Registration");
        patientRegistration.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                patientRegistrationMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ControlLabelMouseEntered(evt);
            }
        });

        accountLabel.setFont(new java.awt.Font("Bell MT", 1, 30)); // NOI18N
        accountLabel.setForeground(new java.awt.Color(255, 255, 255));
        accountLabel.setText("Account");
        accountLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ControlLabelMouseEntered(evt);
            }
        });

        timerhomePanel.setBackground(new java.awt.Color(153, 204, 255));

        patOptionPanell.setBackground(new java.awt.Color(153, 204, 255));

        patOptionpanel2.setBackground(new java.awt.Color(153, 153, 255));

        RadioFAMILY.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup1.add(RadioFAMILY);
        RadioFAMILY.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        RadioFAMILY.setForeground(new java.awt.Color(102, 102, 102));
        RadioFAMILY.setText("FAMILY CARD");

        RadioPersonal.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup1.add(RadioPersonal);
        RadioPersonal.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        RadioPersonal.setForeground(new java.awt.Color(102, 102, 102));
        RadioPersonal.setText("PERSONAL CARD");
        RadioPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioPersonalActionPerformed(evt);
            }
        });

        RadioHMO.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup1.add(RadioHMO);
        RadioHMO.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        RadioHMO.setForeground(new java.awt.Color(102, 102, 102));
        RadioHMO.setText("HMO");

        RadioPostNatal.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup1.add(RadioPostNatal);
        RadioPostNatal.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        RadioPostNatal.setForeground(new java.awt.Color(102, 102, 102));
        RadioPostNatal.setText("POST/ ANTE NATAL");

        patOptionRegProceedButton.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        patOptionRegProceedButton.setText("PROCEED");
        patOptionRegProceedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patOptionRegProceedButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout patOptionpanel2Layout = new javax.swing.GroupLayout(patOptionpanel2);
        patOptionpanel2.setLayout(patOptionpanel2Layout);
        patOptionpanel2Layout.setHorizontalGroup(
            patOptionpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patOptionpanel2Layout.createSequentialGroup()
                .addGap(258, 258, 258)
                .addComponent(patOptionRegProceedButton, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(272, Short.MAX_VALUE))
            .addGroup(patOptionpanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(patOptionpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(patOptionpanel2Layout.createSequentialGroup()
                        .addComponent(RadioPersonal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(RadioPostNatal)
                        .addGap(34, 34, 34))
                    .addGroup(patOptionpanel2Layout.createSequentialGroup()
                        .addGroup(patOptionpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RadioFAMILY)
                            .addComponent(RadioHMO, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        patOptionpanel2Layout.setVerticalGroup(
            patOptionpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, patOptionpanel2Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(RadioHMO)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(RadioFAMILY)
                .addGap(78, 78, 78)
                .addGroup(patOptionpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RadioPersonal)
                    .addComponent(RadioPostNatal))
                .addGap(48, 48, 48)
                .addComponent(patOptionRegProceedButton)
                .addGap(36, 36, 36))
        );

        patOptionPanelerrorLabel.setBackground(new java.awt.Color(153, 204, 255));
        patOptionPanelerrorLabel.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        patOptionPanelerrorLabel.setText("error");

        javax.swing.GroupLayout patOptionPanellLayout = new javax.swing.GroupLayout(patOptionPanell);
        patOptionPanell.setLayout(patOptionPanellLayout);
        patOptionPanellLayout.setHorizontalGroup(
            patOptionPanellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patOptionPanellLayout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .addComponent(patOptionpanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
            .addGroup(patOptionPanellLayout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(patOptionPanelerrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        patOptionPanellLayout.setVerticalGroup(
            patOptionPanellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patOptionPanellLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(patOptionPanelerrorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(patOptionpanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102))
        );

        jLabel1.setBackground(new java.awt.Color(102, 153, 255));
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout HomePanelLayout = new javax.swing.GroupLayout(HomePanel);
        HomePanel.setLayout(HomePanelLayout);
        HomePanelLayout.setHorizontalGroup(
            HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomePanelLayout.createSequentialGroup()
                .addContainerGap(431, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(326, 326, 326))
        );
        HomePanelLayout.setVerticalGroup(
            HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomePanelLayout.createSequentialGroup()
                .addGap(219, 219, 219)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(351, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout backgroundPanelLayout = new javax.swing.GroupLayout(backgroundPanel);
        backgroundPanel.setLayout(backgroundPanelLayout);
        backgroundPanelLayout.setHorizontalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HomePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(patOptionPanell, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        backgroundPanelLayout.setVerticalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HomePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(patOptionPanell, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TimeLabel.setBackground(new java.awt.Color(153, 204, 255));
        TimeLabel.setFont(new java.awt.Font("Bell MT", 1, 36)); // NOI18N
        TimeLabel.setForeground(new java.awt.Color(102, 102, 102));
        TimeLabel.setText("Time");

        patOptionPanelwelcomeLabelLabel.setBackground(new java.awt.Color(153, 204, 255));
        patOptionPanelwelcomeLabelLabel.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        patOptionPanelwelcomeLabelLabel.setForeground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout timerhomePanelLayout = new javax.swing.GroupLayout(timerhomePanel);
        timerhomePanel.setLayout(timerhomePanelLayout);
        timerhomePanelLayout.setHorizontalGroup(
            timerhomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, timerhomePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(patOptionPanelwelcomeLabelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TimeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        timerhomePanelLayout.setVerticalGroup(
            timerhomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timerhomePanelLayout.createSequentialGroup()
                .addGroup(timerhomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TimeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patOptionPanelwelcomeLabelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backgroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout parentpanelLayout = new javax.swing.GroupLayout(parentpanel);
        parentpanel.setLayout(parentpanelLayout);
        parentpanelLayout.setHorizontalGroup(
            parentpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(parentpanelLayout.createSequentialGroup()
                .addGroup(parentpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(parentpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(homesep, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                        .addComponent(homeSep, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(secregsep, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patientRegistration)
                    .addComponent(HomeLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(parentpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(accountLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(allpatsep, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE))
                    .addGroup(parentpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(DiagnosisLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(patSep, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(timerhomePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        parentpanelLayout.setVerticalGroup(
            parentpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(parentpanelLayout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(homesep, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(homeSep, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(patientRegistration, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(secregsep, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(DiagnosisLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(patSep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(accountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(allpatsep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(timerhomePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(parentpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(parentpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 671, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void signupMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signupMouseEntered
         Cursor hand = new Cursor (Cursor.HAND_CURSOR);
         signup.setCursor(hand);
    }//GEN-LAST:event_signupMouseEntered

    private void signupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signupMouseClicked
        // TODO add your handling code here:
        SignupForm signup = new SignupForm();
        signup.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_signupMouseClicked

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // TODO add your handling code here:
        String uname = usernameField.getText();
        String pwd = PasswordField.getText();
        
        if(!validated(uname, pwd))
        {
            usernameField.setText(" ");
            PasswordField.setText("");
            errorLabel.setText("Complete input");
            errorLabel.setVisible(true);           
        }
        else
        {
            DBoperations db = new DBoperations();
            Map <String, String> rst = db.login(uname, pwd);
            if(rst==null)
            {
                usernameField.setText("");
                PasswordField.setText("");
                errorLabel.setText("WRONG USERNAME OR PASSWORD");
                errorLabel.setVisible(true);                
            }
            else
            {
                Runnable time = new Timehandler();
                Thread th = new Thread(time);
                th.start();
                
                String firstN = rst.get("firstName");
                String lastN = rst.get("lastName");
                String Role = rst.get("Role");
                
                mainPanel.setVisible(false);
                parentpanel.setVisible(true);
                patOptionPanell.setVisible(true);
                updatePanel(HomePanel);
                patOptionPanelwelcomeLabelLabel.setText(" WELCOME " +  " " + Role +" " +  firstN + " " + lastN);
            }
        }
    }//GEN-LAST:event_loginButtonActionPerformed
private class Timehandler implements Runnable
 {
        @Override
        public void run() {
            for (;;)
            {
                try {
                    int ch = 10;
                    Calendar cal = new GregorianCalendar();
                    int hr =  cal.get(Calendar.HOUR_OF_DAY);
                    int min =  cal.get(Calendar.MINUTE);
                    int sec =  cal.get(Calendar.SECOND);
                    int day =  cal.get(Calendar.DAY_OF_MONTH);
                    int month = cal.get(Calendar.MONTH);
                    int year = cal.get(Calendar.YEAR);
                    if (ch > hr && ch < min && ch < sec )
                    {
                    String timeString = "0" + hr + ":" + min + ":" + sec ;
                    TimeLabel.setText(timeString);
                    }
                    else if (ch > min && ch < hr & ch < sec )
                    {
                    String timeString = hr + ":" + "0" + min + ":" + sec ;
                    TimeLabel.setText(timeString);
                    }
                    else if (ch > sec && ch < min && ch < hr )
                    {
                    String timeString = hr + ":" + min + ":" + "0" + sec;
                    TimeLabel.setText(timeString);
                    }
                    else if (ch > hr && ch > min && ch < sec )
                    {
                    String timeString = "0" + hr  + ":" + "0" + min + ":" + sec ;
                    TimeLabel.setText(timeString);
                    }
                    else if (ch > hr && ch > sec && ch < min)
                    {
                    String timeString = "0" + hr + ":" + min + ":" + "0" + sec ;
                    TimeLabel.setText(timeString);
                    }
                    else if (ch > min && ch > sec && ch < hr)
                    {
                    String timeString = hr + ":" + "0" + min +":" + "0" + sec;
                    TimeLabel.setText(timeString);
                    } 
                    else if (ch > min && ch > sec && ch > hr)
                    {
                    String timeString = "0" + hr +  ":" + "0" + min +":" + "0" + sec ;
                    TimeLabel.setText(timeString);
                    }   
                    else
                    {
                    String timeString = hr + ":" + min + ":" + sec ;
                    TimeLabel.setText(timeString);
                    }
                   
                    String date =  day + "/" + month + "/" + year ;
                    //DateLabel.setText(date);
                   
                    Thread.sleep(1000);
                } catch (InterruptedException ex) {
                    Logger.getLogger(LoginFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }   
 }
    private void ControlLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ControlLabelMouseEntered
        // TODO add your handling code here:
        Cursor handCursor = new Cursor (Cursor.HAND_CURSOR);
        Object obj = evt.getSource();
        JLabel lb = (JLabel) obj;
        lb.setCursor(handCursor);
    }//GEN-LAST:event_ControlLabelMouseEntered

    private void RadioPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioPersonalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioPersonalActionPerformed

    private void HomeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeLabelMouseClicked
        // TODO add your handling code here:
             updatePanel(HomePanel);
    }//GEN-LAST:event_HomeLabelMouseClicked

    private void patientRegistrationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_patientRegistrationMouseClicked
        // TODO add your handling code here:
             updatePanel(patOptionPanell);
             patOptionPanelerrorLabel.setVisible(false);
             patOptionPanell.setVisible(true);
           
    }//GEN-LAST:event_patientRegistrationMouseClicked

    public JPanel getPatOptionPanell() {
        return patOptionPanell;
    }

    private void patOptionRegProceedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patOptionRegProceedButtonActionPerformed
        // TODO add your handling code here:
       
        if (RadioPersonal.isSelected())
        {   
        OptionSelectPersonal nn = new OptionSelectPersonal(this);
              updatePanel(nn);
        }
        else if (RadioFAMILY.isSelected())
        {
       OptionSelectFamily nn = new OptionSelectFamily(this);
              updatePanel(nn);
        }
        else if (RadioHMO.isSelected())
        {
       OptionSelectHMO nn = new OptionSelectHMO(this);
              updatePanel(nn);
        }
        else if (RadioPostNatal.isSelected())
        {
        OptionSelectAnteNatalPanel nn = new OptionSelectAnteNatalPanel(this);
              updatePanel(nn);
        }
        else
        {
            patOptionPanelerrorLabel.setVisible(true);
            patOptionPanelerrorLabel.setText("Please Select an Option");
        }

    }//GEN-LAST:event_patOptionRegProceedButtonActionPerformed

    private void DiagnosisLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DiagnosisLabelMouseClicked
        // TODO add your handling code here:
        newReturningPatientPanel nrt = new newReturningPatientPanel(this);
        updatePanel(nrt);
    }//GEN-LAST:event_DiagnosisLabelMouseClicked
     private boolean validated(String un, String pd)
        {
            if(un.isEmpty() || pd.isEmpty())
            {
                return false;
            }
            return true;
        }
    /**
     * @param args the command line arguments
     */
    
    /**
     *
     * @param currentPanel
     * @param args the command line arguments
     */
    public void updatePanel (JPanel currentPanel)
    {
        backgroundPanel.removeAll();   
        GroupLayout l = (GroupLayout) backgroundPanel.getLayout();      
                l.setHorizontalGroup(
                l.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(currentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
                l.setVerticalGroup(
                l.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(currentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)           
        );  
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
    try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DiagnosisLabel;
    private javax.swing.JLabel HomeLabel;
    private javax.swing.JPanel HomePanel;
    private javax.swing.JLabel MAINFRAMEIMAGELabel;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JRadioButton RadioFAMILY;
    private javax.swing.JRadioButton RadioHMO;
    private javax.swing.JRadioButton RadioPersonal;
    private javax.swing.JRadioButton RadioPostNatal;
    private javax.swing.JLabel TimeLabel;
    private javax.swing.JLabel accountLabel;
    private javax.swing.JSeparator allpatsep;
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel companylabel;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JSeparator homeSep;
    private javax.swing.JSeparator homesep;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton loginButton;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel parentpanel;
    private javax.swing.JLabel password1;
    private javax.swing.JPanel passwordPanel;
    private javax.swing.JLabel patOptionPanelerrorLabel;
    private javax.swing.JPanel patOptionPanell;
    private javax.swing.JLabel patOptionPanelwelcomeLabelLabel;
    private javax.swing.JButton patOptionRegProceedButton;
    private javax.swing.JPanel patOptionpanel2;
    private javax.swing.JSeparator patSep;
    private javax.swing.JLabel patientRegistration;
    private javax.swing.JSeparator secregsep;
    private javax.swing.JLabel signup;
    private javax.swing.JPanel subPanel;
    private javax.swing.JPanel timerhomePanel;
    private javax.swing.JLabel urAccount;
    private javax.swing.JLabel username;
    private javax.swing.JTextField usernameField;
    private javax.swing.JPanel usernamePanel;
    // End of variables declaration//GEN-END:variables
}
