/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.health.hospital;

import java.awt.Color;
import java.awt.Font;
import javax.swing.JTextField;
import org.jdesktop.swingx.prompt.PromptSupport;

/**
 *
 * @author chinex
 */
public class newReturningPatientPanel extends javax.swing.JPanel {

    /**
     * Creates new form newReturningPatientPanel
     */
    private final LoginFrame loginFrame; 
    public newReturningPatientPanel(LoginFrame loginFrame) {
        initComponents();
        textCustomise("Enter Returning Student Card No. ",ReturningPatientTextField);
        this.loginFrame = loginFrame;
    }

    private void textCustomise(String text, JTextField component)
    {
        PromptSupport.setPrompt(text, component);
        PromptSupport.setFocusBehavior(PromptSupport.FocusBehavior.HIDE_PROMPT, component);
        PromptSupport.setFocusBehavior(PromptSupport.FocusBehavior.SHOW_PROMPT, component);
        PromptSupport.setFontStyle(Font.BOLD, component);
        PromptSupport.setForeground(Color.darkGray, component);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        newTreatment = new javax.swing.JButton();
        SearchReturningPatient1 = new javax.swing.JButton();
        ReturningPatientTextField = new javax.swing.JTextField();
        ExistingTreatmentLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 153, 153));

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));

        newTreatment.setBackground(new java.awt.Color(153, 153, 153));
        newTreatment.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        newTreatment.setText("New Treatment");
        newTreatment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newTreatmentActionPerformed(evt);
            }
        });

        SearchReturningPatient1.setBackground(new java.awt.Color(153, 153, 153));
        SearchReturningPatient1.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        SearchReturningPatient1.setText("SEARCH");
        SearchReturningPatient1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        SearchReturningPatient1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchReturningPatient1ActionPerformed(evt);
            }
        });

        ReturningPatientTextField.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        ReturningPatientTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        ExistingTreatmentLabel.setFont(new java.awt.Font("Bell MT", 1, 30)); // NOI18N
        ExistingTreatmentLabel.setForeground(new java.awt.Color(102, 102, 102));
        ExistingTreatmentLabel.setText("On-going Treatment");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(newTreatment)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(ExistingTreatmentLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(136, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(ReturningPatientTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(131, 131, 131))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(SearchReturningPatient1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(232, 232, 232))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newTreatment, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addComponent(ExistingTreatmentLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ReturningPatientTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SearchReturningPatient1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(104, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(115, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void newTreatmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newTreatmentActionPerformed
        // TODO add your handling code here:
        NewtreatmentregPanel newtreatmentreg = new NewtreatmentregPanel(loginFrame);
        loginFrame.updatePanel(newtreatmentreg);
    }//GEN-LAST:event_newTreatmentActionPerformed

    private void SearchReturningPatient1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchReturningPatient1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_SearchReturningPatient1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ExistingTreatmentLabel;
    private javax.swing.JTextField ReturningPatientTextField;
    private javax.swing.JButton SearchReturningPatient1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton newTreatment;
    // End of variables declaration//GEN-END:variables
}
