/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.health.hospital;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author chinex
 */
public class NewtreatmentregPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewtreatmentregPanel
     */
    private final LoginFrame loginFrame;
    public NewtreatmentregPanel(LoginFrame loginFrame) {
        initComponents();
        
       this.loginFrame=loginFrame; 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newtreatmentregpatientnametextfield = new javax.swing.JTextField();
        newtreatmentregCardNotextfield = new javax.swing.JTextField();
        newtreatmentregDateChoosertextfield = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        newtreatmentregpatientsymptontextarea = new javax.swing.JTextArea();
        newtreatmentregBackButton = new javax.swing.JButton();
        newtreatmentregSaveButton = new javax.swing.JButton();
        newtreatmentregCardnoLabel = new javax.swing.JLabel();
        newtreatmentregCardnoLabel1 = new javax.swing.JLabel();
        newtreatmentregCardnoLabel2 = new javax.swing.JLabel();
        newtreatmentregCardnoLabel3 = new javax.swing.JLabel();
        newtreatmentregCardnoLabel4 = new javax.swing.JLabel();
        FOCUSlostLabel = new javax.swing.JLabel();
        newpatientregcardsignLabel = new javax.swing.JLabel();
        newpatientregcardwarningLabel = new javax.swing.JLabel();
        newtreatmentregdobDateChooser = new com.toedter.calendar.JDateChooser();

        setBackground(new java.awt.Color(153, 153, 153));

        newtreatmentregpatientnametextfield.setFont(new java.awt.Font("Bell MT", 1, 15)); // NOI18N

        newtreatmentregCardNotextfield.setFont(new java.awt.Font("Bell MT", 1, 15)); // NOI18N
        newtreatmentregCardNotextfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                newtreatmentregCardNotextfieldFocusLost(evt);
            }
        });

        newtreatmentregpatientsymptontextarea.setColumns(20);
        newtreatmentregpatientsymptontextarea.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        newtreatmentregpatientsymptontextarea.setRows(5);
        jScrollPane1.setViewportView(newtreatmentregpatientsymptontextarea);

        newtreatmentregBackButton.setFont(new java.awt.Font("Bell MT", 1, 20)); // NOI18N
        newtreatmentregBackButton.setText("BACK");
        newtreatmentregBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newtreatmentregBackButtonActionPerformed(evt);
            }
        });

        newtreatmentregSaveButton.setFont(new java.awt.Font("Bell MT", 1, 22)); // NOI18N
        newtreatmentregSaveButton.setText("Save");
        newtreatmentregSaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newtreatmentregSaveButtonActionPerformed(evt);
            }
        });

        newtreatmentregCardnoLabel.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        newtreatmentregCardnoLabel.setText("Start date");

        newtreatmentregCardnoLabel1.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        newtreatmentregCardnoLabel1.setText("Patient Name");

        newtreatmentregCardnoLabel2.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        newtreatmentregCardnoLabel2.setText("Patient Symptons");

        newtreatmentregCardnoLabel3.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        newtreatmentregCardnoLabel3.setText("Date Of Birth");

        newtreatmentregCardnoLabel4.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        newtreatmentregCardnoLabel4.setText("Card No.");

        newpatientregcardwarningLabel.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        newpatientregcardwarningLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newpatientregcardwarningLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newtreatmentregSaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(newtreatmentregBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)))
                .addGap(318, 318, 318))
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(newtreatmentregDateChoosertextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(newtreatmentregCardNotextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(newpatientregcardsignLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(newtreatmentregCardnoLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(newtreatmentregCardnoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(newtreatmentregCardnoLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(newtreatmentregpatientnametextfield, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                                        .addComponent(newtreatmentregCardnoLabel1)
                                        .addComponent(newtreatmentregdobDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addGap(45, 45, 45))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(newtreatmentregCardnoLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(newpatientregcardwarningLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(FOCUSlostLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(108, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newtreatmentregCardnoLabel4)
                    .addComponent(newtreatmentregCardnoLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newtreatmentregpatientnametextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(newtreatmentregCardNotextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(newpatientregcardsignLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(FOCUSlostLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 16, Short.MAX_VALUE)
                    .addComponent(newpatientregcardwarningLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newtreatmentregCardnoLabel3)
                    .addComponent(newtreatmentregCardnoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(newtreatmentregdobDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(newtreatmentregDateChoosertextfield, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE))
                .addGap(50, 50, 50)
                .addComponent(newtreatmentregCardnoLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newtreatmentregSaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(newtreatmentregBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(107, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void newtreatmentregCardNotextfieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_newtreatmentregCardNotextfieldFocusLost
        // TODO add your handling code here:
        String card = newtreatmentregCardNotextfield.getText();
        if (!card.isEmpty())
        {
            DBoperations db = new DBoperations();
            boolean reply = db.cardValid(card);
            
            if(reply)
            {
                newpatientregcardsignLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\chinex\\Documents\\NetBeansProjects\\goodsign.png"));
                newpatientregcardwarningLabel.setText(" ");
            }
            else
            {
                 newpatientregcardsignLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\chinex\\Documents\\NetBeansProjects\\badsign.png"));
                 newpatientregcardwarningLabel.setText("Invalid Card Number,Please click link to get registered");
            }
        }
    }//GEN-LAST:event_newtreatmentregCardNotextfieldFocusLost

    private void newpatientregcardwarningLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newpatientregcardwarningLabelMouseClicked
        // TODO add your handling code here:
        JPanel upPanel = loginFrame.getPatOptionPanell();
        loginFrame.updatePanel(upPanel);
    }//GEN-LAST:event_newpatientregcardwarningLabelMouseClicked

    private void newtreatmentregSaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newtreatmentregSaveButtonActionPerformed
        // TODO add your handling code here:
      
        
       String cardNo    =    newtreatmentregCardNotextfield.getText();
       String fullname  =    newtreatmentregpatientnametextfield.getText();
       Date startDate = newtreatmentregDateChoosertextfield.getDate();
       Date dob =  newtreatmentregdobDateChooser.getDate();
       String patsym = newtreatmentregpatientsymptontextarea.getText();
       
       SimpleDateFormat ft = new SimpleDateFormat ("yyyy-MM-dd");
       
       String startDateStr = ft.format(startDate);
       String dobStr = ft.format(dob);
       
       DBoperations db = new DBoperations();
       int cardCount =  db.getCardNoCount(cardNo);
       cardCount++;
       
       String CardId = cardNo.concat("_" + cardCount);
       String reply = db.saveOngoingTreatmentRecord(CardId, cardNo, fullname, startDateStr, dobStr, patsym);
       if (reply.equals("success"))
       {
           HashMap<String, String[]> objMap = db.getAllTreatmentRecordByCardNo(cardNo);
           TabularcardRecordPanel tbPanel = new TabularcardRecordPanel(objMap,cardNo);
           loginFrame.updatePanel(tbPanel);
       }
       else
       {
           
       }
       newtreatmentregCardNotextfield.setText("");
       newtreatmentregpatientnametextfield.setText("");
       newtreatmentregDateChoosertextfield.setDate(null);
       newtreatmentregdobDateChooser.setDate(null);
       newtreatmentregpatientsymptontextarea.setText(""); 
    }//GEN-LAST:event_newtreatmentregSaveButtonActionPerformed

    private void newtreatmentregBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newtreatmentregBackButtonActionPerformed
        // TODO add your handling code here:
        newReturningPatientPanel upPanel = new newReturningPatientPanel(loginFrame);
        loginFrame.updatePanel(upPanel);
    }//GEN-LAST:event_newtreatmentregBackButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FOCUSlostLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel newpatientregcardsignLabel;
    private javax.swing.JLabel newpatientregcardwarningLabel;
    private javax.swing.JButton newtreatmentregBackButton;
    private javax.swing.JTextField newtreatmentregCardNotextfield;
    private javax.swing.JLabel newtreatmentregCardnoLabel;
    private javax.swing.JLabel newtreatmentregCardnoLabel1;
    private javax.swing.JLabel newtreatmentregCardnoLabel2;
    private javax.swing.JLabel newtreatmentregCardnoLabel3;
    private javax.swing.JLabel newtreatmentregCardnoLabel4;
    private com.toedter.calendar.JDateChooser newtreatmentregDateChoosertextfield;
    private javax.swing.JButton newtreatmentregSaveButton;
    private com.toedter.calendar.JDateChooser newtreatmentregdobDateChooser;
    private javax.swing.JTextField newtreatmentregpatientnametextfield;
    private javax.swing.JTextArea newtreatmentregpatientsymptontextarea;
    // End of variables declaration//GEN-END:variables
}
