/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.health.hospital;

import java.awt.Color;
import java.awt.Font;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import org.jdesktop.swingx.prompt.PromptSupport;

/**
 *
 * @author chinex
 */
public class OptionSelectHMO extends javax.swing.JPanel {

    /**
     * Creates new form OptionSelectHMO
     */
     private final LoginFrame loginFrame;
    public OptionSelectHMO(LoginFrame loginFrame) 
    {
        initComponents();
        textCustomise("Enter Card No.", HMOBenefactorCardNoTextField);
        textCustomise("Enter Phone Number", HMOBenefactorPhoneNumberTextField);
        textCustomise("Enter Occupation", HMObenefactorOccupationTextField);
        textCustomise("Enter Age", HMObenefactorAgeTextField1);
        textCustomise("Enter Enrolee ID", HMObenefactorEnroleeTextField);
        textCustomise("Enter HealthCare Plan", HMObenefactorPlanTextField);
        textCustomise("Enter Company Name", HMOCompanyNameTextField);
        textCustomise("Enter Address", HMObenefactorAddressTextField);
        textCustomise("Enter HMO Name", HMONameTextField1);
        textCustomise("Enter Next of Kin Name", HMOBenefactorKinnameTextField);
        textCustomise("Enter Relationship with Next of kin", HMOBenefactorKinRelationshipTextField1);
        textCustomise("Enter Phone Number", HMOBenefactorKinphoneTextField1);
        textCustomise("Enter Next Of Kin Address", HMOBenefactorKinAddressTextField);       
        this.loginFrame=loginFrame;
    }

    private void textCustomise(String text, JTextField component)
    {
        PromptSupport.setPrompt(text, component);
        PromptSupport.setFocusBehavior(PromptSupport.FocusBehavior.HIDE_PROMPT, component);
        PromptSupport.setFocusBehavior(PromptSupport.FocusBehavior.SHOW_PROMPT, component);
        PromptSupport.setFontStyle(Font.BOLD, component);
        PromptSupport.setForeground(Color.darkGray, component);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HMOCardPanel = new javax.swing.JPanel();
        HMObenefactorlabel = new javax.swing.JLabel();
        HMOcompanylabel = new javax.swing.JLabel();
        HMObenefactorstateComboBox = new javax.swing.JComboBox();
        HMObenefactormaritalComboBox = new javax.swing.JComboBox();
        HMObenefactorreligioncombobox = new javax.swing.JComboBox();
        HMObenefactorLnationalityComboBox = new javax.swing.JComboBox();
        HMOBenefactorKinAddressTextField = new javax.swing.JTextField();
        HMOCompanyNameTextField = new javax.swing.JTextField();
        HMOBenefactorKinnameTextField = new javax.swing.JTextField();
        HMObenefactorAddressTextField = new javax.swing.JTextField();
        HMOBenefactorCardNoTextField = new javax.swing.JTextField();
        HMOBenefactorPhoneNumberTextField = new javax.swing.JTextField();
        HMObenefactorEnroleeTextField = new javax.swing.JTextField();
        HMObenefactorOccupationTextField = new javax.swing.JTextField();
        HMObenefactorPlanTextField = new javax.swing.JTextField();
        HMOSaveButton = new javax.swing.JButton();
        HMOLBackToPatOption1Button = new javax.swing.JButton();
        HMObenefactorAgeTextField1 = new javax.swing.JTextField();
        HMOBenefactorKinphoneTextField1 = new javax.swing.JTextField();
        HMOBenefactorKinRelationshipTextField1 = new javax.swing.JTextField();
        NextOfKinLabel = new javax.swing.JLabel();
        HMONameTextField1 = new javax.swing.JTextField();
        HMOStartDateChooser = new com.toedter.calendar.JDateChooser();
        HMOEndDateChooser = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 153, 153));
        setPreferredSize(new java.awt.Dimension(836, 623));

        HMOCardPanel.setBackground(new java.awt.Color(102, 153, 255));

        HMObenefactorlabel.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        HMObenefactorlabel.setText("BENEFACTOR");

        HMOcompanylabel.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        HMOcompanylabel.setText("HMO DETAILS");

        HMObenefactorstateComboBox.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        HMObenefactorstateComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select State" }));

        HMObenefactormaritalComboBox.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        HMObenefactormaritalComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Marital Status", "Married", "Single" }));

        HMObenefactorreligioncombobox.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        HMObenefactorreligioncombobox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Religion", "Christian", "Muslim", "Traditional", "Buddism", "Judaism", "Hinduism", "Others" }));

        HMObenefactorLnationalityComboBox.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        HMObenefactorLnationalityComboBox.setMaximumRowCount(100);
        HMObenefactorLnationalityComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Nationality", "AF  Afghanistan", "AL  Albania", "DZ  Algeria", "AS  American Samoa", "AD  Andorra", "AO  Angola", "AI  Anguilla", "AQ  Antarctica", "AG  Antigua and Barbuda", "AR  Argentina", "AM  Armenia", "AW  Aruba", "AU  Australia", "AT  Austria", "AZ  Azerbaijan", "BS  Bahamas", "BH  Bahrain", "BD  Bangladesh", "BB  Barbados", "BY  Belarus", "BE  Belgium", "BZ  Belize", "BJ  Benin", "BM  Bermuda", "BT  Bhutan", "BO  Bolivia", "BA  Bosnia and Herzegovina", "BW  Botswana", "BV  Bouvet Island", "BR  Brazil", "IO  British Indian Ocean Territory", "VG  British Virgin Islands", "BN  Brunei", "BG  Bulgaria", "BF  Burkina Faso", "BI  Burundi", "KH  Cambodia", "CM  Cameroon", "CA  Canada", "CV  Cape Verde", "KY  Cayman Islands", "CF  Central African Republic", "TD  Chad", "CL  Chile", "CN  China", "CX  Christmas Island", "CC  Cocos Islands", "CO  Colombia", "KM  Comoros", "CG  Congo", "CK  Cook Islands", "CR  Costa Rica", "HR  Croatia", "CU  Cuba", "CY  Cyprus", "CZ  Czech Republic", "CI  Côte d'Ivoire", "DK  Denmark", "DJ  Djibouti", "DM  Dominica", "DO  Dominican Republic", "EC  Ecuador", "EG  Egypt", "SV  El Salvador", "GQ  Equatorial Guinea", "ER  Eritrea", "EE  Estonia", "ET  Ethiopia", "FK  Falkland Islands", "FO  Faroe Islands", "FJ  Fiji", "FI  Finland", "FR  France", "GF  French Guiana", "PF  French Polynesia", "TF  French Southern Territories", "GA  Gabon", "GM  Gambia", "GE  Georgia", "DE  Germany", "GH  Ghana", "GI  Gibraltar", "GR  Greece", "GL  Greenland", "GD  Grenada", "GP  Guadeloupe", "GU  Guam", "GT  Guatemala", "GN  Guinea", "GW  Guinea-Bissau", "GY  Guyana", "HT  Haiti", "HM  Heard Island And McDonald Islands", "HN  Honduras", "HK  Hong Kong", "HU  Hungary", "IS  Iceland", "IN  India", "ID  Indonesia", "IR  Iran", "IQ  Iraq", "IE  Ireland", "IL  Israel", "IT  Italy", "JM  Jamaica", "JP  Japan", "JO  Jordan", "KZ  Kazakhstan", "KE  Kenya", "KI  Kiribati", "KW  Kuwait", "KG  Kyrgyzstan", "LA  Laos", "LV  Latvia", "LB  Lebanon", "LS  Lesotho", "LR  Liberia", "LY  Libya", "LI  Liechtenstein", "LT  Lithuania", "LU  Luxembourg", "MO  Macao", "MK  Macedonia", "MG  Madagascar", "MW  Malawi", "MY  Malaysia", "MV  Maldives", "ML  Mali", "MT  Malta", "MH  Marshall Islands", "MQ  Martinique", "MR  Mauritania", "MU  Mauritius", "YT  Mayotte", "MX  Mexico", "FM  Micronesia", "MD  Moldova", "MC  Monaco", "MN  Mongolia", "ME  Montenegro", "MS  Montserrat", "MA  Morocco", "MZ  Mozambique", "MM  Myanmar", "NA  Namibia", "NR  Nauru", "NP  Nepal", "NL  Netherlands", "AN  Netherlands Antilles", "NC  New Caledonia", "NZ  New Zealand", "NI  Nicaragua", "NE  Niger", "NG  Nigeria", "NU  Niue", "NF  Norfolk Island", "KP  North Korea", "MP  Northern Mariana Islands", "NO  Norway", "OM  Oman", "PK  Pakistan", "PW  Palau", "PS  Palestine", "PA  Panama", "PG  Papua New Guinea", "PY  Paraguay", "PE  Peru", "PH  Philippines", "PN  Pitcairn", "PL  Poland", "PT  Portugal", "PR  Puerto Rico", "QA  Qatar", "RE  Reunion", "RO  Romania", "RU  Russia", "RW  Rwanda", "SH  Saint Helena", "KN  Saint Kitts And Nevis", "LC  Saint Lucia", "PM  Saint Pierre And Miquelon", "VC  Saint Vincent And The Grenadines", "WS  Samoa", "SM  San Marino", "ST  Sao Tome And Principe", "SA  Saudi Arabia", "SN  Senegal", "RS  Serbia", "CS  Serbia and Montenegro", "SC  Seychelles", "SL  Sierra Leone", "SG  Singapore", "SK  Slovakia", "SI  Slovenia", "SB  Solomon Islands", "SO  Somalia", "ZA  South Africa", "GS  South Georgia And The South Sandwich", "Islands KR  South Korea", "ES  Spain", "LK  Sri Lanka", "SD  Sudan", "SR  Suriname", "SJ  Svalbard And Jan Mayen", "SZ  Swaziland", "SE  Sweden", "CH  Switzerland", "SY  Syria", "TW  Taiwan", "TJ  Tajikistan", "TZ  Tanzania", "TH  Thailand", "CD  The Democratic Republic Of Congo", "TL  Timor-Leste", "TG  Togo", "TK  Tokelau", "TO  Tonga", "TT  Trinidad and Tobago", "TN  Tunisia", "TR  Turkey", "TM  Turkmenistan", "TC  Turks And Caicos Islands", "TV  Tuvalu", "VI  U.S. Virgin Islands", "UG  Uganda", "UA  Ukraine", "AE  United Arab Emirates", "GB  United Kingdom", "US  United States", "UM  United States Minor Outlying Islands", "UY  Uruguay", "UZ  Uzbekistan", "VU  Vanuatu", "VA  Vatican", "VE  Venezuela", "VN  Vietnam", "WF  Wallis And Futuna", "EH  Western Sahara", "YE  Yemen", "ZM  Zambia", "ZW  Zimbabwe", "AX  Åland Islands" }));

        HMOSaveButton.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        HMOSaveButton.setText("SAVE");
        HMOSaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HMOSaveButtonActionPerformed(evt);
            }
        });

        HMOLBackToPatOption1Button.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        HMOLBackToPatOption1Button.setText("BACK");
        HMOLBackToPatOption1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HMOLBackToPatOption1ButtonActionPerformed(evt);
            }
        });

        NextOfKinLabel.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        NextOfKinLabel.setText("NEXT OF KIN");

        javax.swing.GroupLayout HMOCardPanelLayout = new javax.swing.GroupLayout(HMOCardPanel);
        HMOCardPanel.setLayout(HMOCardPanelLayout);
        HMOCardPanelLayout.setHorizontalGroup(
            HMOCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HMOCardPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(HMOCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HMOCardPanelLayout.createSequentialGroup()
                        .addGroup(HMOCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(HMOCardPanelLayout.createSequentialGroup()
                                .addGap(91, 91, 91)
                                .addComponent(HMOLBackToPatOption1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(258, 258, 258)
                                .addComponent(HMOSaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(HMOCardPanelLayout.createSequentialGroup()
                                .addGroup(HMOCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(HMOBenefactorKinAddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(HMONameTextField1))
                                .addGap(29, 29, 29)
                                .addGroup(HMOCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(HMOCompanyNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(HMOBenefactorKinRelationshipTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(32, Short.MAX_VALUE))
                    .addGroup(HMOCardPanelLayout.createSequentialGroup()
                        .addGroup(HMOCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(HMOcompanylabel)
                            .addComponent(NextOfKinLabel)
                            .addGroup(HMOCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, HMOCardPanelLayout.createSequentialGroup()
                                    .addComponent(HMOBenefactorKinnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(HMOBenefactorKinphoneTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(HMObenefactorAddressTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 668, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, HMOCardPanelLayout.createSequentialGroup()
                                    .addGroup(HMOCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(HMOStartDateChooser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(HMOCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(HMObenefactorstateComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(HMObenefactorEnroleeTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(HMObenefactorOccupationTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(HMObenefactorreligioncombobox, javax.swing.GroupLayout.Alignment.LEADING, 0, 320, Short.MAX_VALUE))
                                        .addComponent(HMObenefactorlabel)
                                        .addComponent(HMOBenefactorCardNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(28, 28, 28)
                                    .addGroup(HMOCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(HMObenefactorAgeTextField1)
                                        .addGroup(HMOCardPanelLayout.createSequentialGroup()
                                            .addGroup(HMOCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(HMOEndDateChooser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(HMOBenefactorPhoneNumberTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(HMObenefactorLnationalityComboBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(HMObenefactormaritalComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(HMObenefactorPlanTextField, javax.swing.GroupLayout.Alignment.LEADING))
                                            .addGap(0, 0, Short.MAX_VALUE))))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        HMOCardPanelLayout.setVerticalGroup(
            HMOCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HMOCardPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(HMObenefactorlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(HMOCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HMOCardPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(HMOCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(HMOBenefactorPhoneNumberTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                            .addComponent(HMOBenefactorCardNoTextField))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(HMOCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(HMObenefactorEnroleeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HMObenefactorPlanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(HMOCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(HMObenefactorOccupationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HMObenefactorAgeTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(HMOStartDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HMOCardPanelLayout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(HMOEndDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(HMOCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HMObenefactorreligioncombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HMObenefactorLnationalityComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(HMOCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(HMObenefactormaritalComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HMObenefactorstateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(HMObenefactorAddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NextOfKinLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(HMOCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HMOBenefactorKinnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HMOBenefactorKinphoneTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(HMOCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HMOBenefactorKinRelationshipTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HMOBenefactorKinAddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HMOcompanylabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(HMOCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HMOCompanyNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HMONameTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(HMOCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HMOSaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HMOLBackToPatOption1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jLabel1.setFont(new java.awt.Font("Bell MT", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 204, 255));
        jLabel1.setText("COMPANY / BENEFACTOR DETAILS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(HMOCardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HMOCardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void HMOLBackToPatOption1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HMOLBackToPatOption1ButtonActionPerformed
        // TODO add your handling code here:
        JPanel optPanel = loginFrame.getPatOptionPanell();
        loginFrame.updatePanel(optPanel);
    }//GEN-LAST:event_HMOLBackToPatOption1ButtonActionPerformed

    private void HMOSaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HMOSaveButtonActionPerformed
        // TODO add your handling code here:
       
        
        String cardNo = HMOBenefactorCardNoTextField.getText();
        String phone = HMOBenefactorPhoneNumberTextField.getText();
        String occupation = HMObenefactorOccupationTextField.getText();
        String addr = HMObenefactorAddressTextField.getText();
        String mStatus = (String) HMObenefactormaritalComboBox.getSelectedItem();
        String religion = (String) HMObenefactorreligioncombobox.getSelectedItem();
        String nationality = (String)HMObenefactorLnationalityComboBox.getSelectedItem();
        String state = (String)HMObenefactorstateComboBox.getSelectedItem();
        String kinName = HMOBenefactorKinnameTextField.getText();
        String kinAddr = HMOBenefactorKinAddressTextField.getText();
        String kinPhone = HMOBenefactorKinphoneTextField1.getText();
        String kinRelation = HMOBenefactorKinRelationshipTextField1.getText();
        String EnrolID = HMObenefactorEnroleeTextField.getText();
        String HMOplan = HMObenefactorPlanTextField.getText();
        String comName = HMOCompanyNameTextField.getText();
        String Hmoname = HMONameTextField1.getText();
        
        if(!validated(cardNo, phone, occupation, addr, mStatus, religion, nationality, state, kinName, kinAddr, kinPhone, kinRelation, EnrolID, HMOplan, Hmoname, comName))
        {
            JOptionPane.showMessageDialog(loginFrame, "Fill in all Spaces"); 
        }
        else
        {
        int age = Integer.parseInt(HMObenefactorAgeTextField1.getText());
        SimpleDateFormat sFormat = new SimpleDateFormat("yyyy-MM-dd");
        Date dateOfstart = HMOStartDateChooser.getDate();
        Date dateOfend = HMOEndDateChooser.getDate();
        String dateOfRegstart = sFormat.format(dateOfstart);
        String dateOfRegend = sFormat.format(dateOfend); 
        DBoperations db = new DBoperations();
        db.HMOcardsave(cardNo, phone, addr, occupation, dateOfRegstart,dateOfRegend, mStatus, age, religion, nationality, state, kinName, kinAddr, 
                       kinPhone, kinRelation,EnrolID,HMOplan,Hmoname,comName);
        
        HMOBenefactorCardNoTextField.setText("");
        HMOBenefactorPhoneNumberTextField.setText("");
        HMObenefactorOccupationTextField.setText("");
        HMObenefactorAddressTextField.setText("");
        HMOStartDateChooser.setDate(null);
        HMOEndDateChooser.setDate(null);
        HMObenefactorAgeTextField1.setText("");
        HMObenefactormaritalComboBox.setSelectedItem("Marital Status");
        HMObenefactorreligioncombobox.setSelectedItem("Select Religion");
        HMObenefactorLnationalityComboBox.setSelectedItem("Select Nationality");
        HMObenefactorstateComboBox.setSelectedItem("Select State");
        HMOBenefactorKinnameTextField.setText("");
        HMOBenefactorKinAddressTextField.setText("");
        HMOBenefactorKinphoneTextField1.setText("");
        HMOBenefactorKinRelationshipTextField1.setText("");
        HMObenefactorEnroleeTextField.setText("");
        HMObenefactorPlanTextField.setText("");
        HMOCompanyNameTextField.setText("");
        HMONameTextField1.setText("");
        }
    }//GEN-LAST:event_HMOSaveButtonActionPerformed
private boolean 
validated(String cardNo,String phone, String occupation ,String addr ,String mStatus,String religion, 
String nationality, String state ,String kinName, String kinAddr, String kinPhone,String kinRelation ,
String EnrolID, String HMOplan, String Hmoname,String comName)
  {
    if(cardNo.isEmpty()||phone.isEmpty()||occupation.isEmpty()||addr.isEmpty()||mStatus.isEmpty()||religion.isEmpty()||nationality.isEmpty()||
       state.isEmpty()||kinName.isEmpty()||kinAddr.isEmpty()||kinPhone.isEmpty()||kinRelation.isEmpty()||HMOplan.isEmpty()||EnrolID.isEmpty()||Hmoname.isEmpty()||comName.isEmpty())
    {
        return false;
    }
    return true;
  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField HMOBenefactorCardNoTextField;
    private javax.swing.JTextField HMOBenefactorKinAddressTextField;
    private javax.swing.JTextField HMOBenefactorKinRelationshipTextField1;
    private javax.swing.JTextField HMOBenefactorKinnameTextField;
    private javax.swing.JTextField HMOBenefactorKinphoneTextField1;
    private javax.swing.JTextField HMOBenefactorPhoneNumberTextField;
    private javax.swing.JPanel HMOCardPanel;
    private javax.swing.JTextField HMOCompanyNameTextField;
    private com.toedter.calendar.JDateChooser HMOEndDateChooser;
    private javax.swing.JButton HMOLBackToPatOption1Button;
    private javax.swing.JTextField HMONameTextField1;
    private javax.swing.JButton HMOSaveButton;
    private com.toedter.calendar.JDateChooser HMOStartDateChooser;
    private javax.swing.JTextField HMObenefactorAddressTextField;
    private javax.swing.JTextField HMObenefactorAgeTextField1;
    private javax.swing.JTextField HMObenefactorEnroleeTextField;
    private javax.swing.JComboBox HMObenefactorLnationalityComboBox;
    private javax.swing.JTextField HMObenefactorOccupationTextField;
    private javax.swing.JTextField HMObenefactorPlanTextField;
    private javax.swing.JLabel HMObenefactorlabel;
    private javax.swing.JComboBox HMObenefactormaritalComboBox;
    private javax.swing.JComboBox HMObenefactorreligioncombobox;
    private javax.swing.JComboBox HMObenefactorstateComboBox;
    private javax.swing.JLabel HMOcompanylabel;
    private javax.swing.JLabel NextOfKinLabel;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
