/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.health.hospital;

import java.awt.Color;
import java.awt.Font;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import org.jdesktop.swingx.prompt.PromptSupport;

/**
 *
 * @author chinex
 */
public class OptionSelectAnteNatalPanel extends javax.swing.JPanel {

    /**
     * Creates new form OptionSelectAnteNatalPanel
     */
     private LoginFrame loginFrame;
    public OptionSelectAnteNatalPanel(LoginFrame loginFrame) {
        initComponents(); 
        textCustomise("Enter Card No.", ANTENATALCardNoTextField);
        textCustomise("Enter Phone Number", ANTENATALPhoneNumberTextField);
        textCustomise("Enter Occupation", ANTENATALOccupationTextField);
        textCustomise("Enter Age", ANTENATALAgeTextField);
        textCustomise("Enter Spouse's Address", ANTENATALspouseAddressTextField);
        textCustomise("Enter Spouse's full Name", ANTENATALspouseNameTextField1);
        textCustomise("Enter Address", ANTENATALAddressTextField);
        textCustomise("Enter Spouse's Occupation", ANTENATALspouseOccupationTextField);
        textCustomise("Enter Spouse's Phone Number", ANTENATALspousephoneTextField);
        textCustomise("Emergency Contact's Name", ANTENATALemergencycontact1nameTextField);
        textCustomise("Contact's Phone number", ANTENATALemergencycontact1phoneTextField);
        textCustomise("Contact's Relationship", ANTENATALemergencycontact1relationshipTextField); 
        textCustomise("2nd Emergency Contact's Name", ANTENATALemergencycontact2nameTextField);
        textCustomise("2nd Contact's Phone Number", ANTENATALemergencycontact2phoneTextField);
        textCustomise("2nd Contact's Address", ANTENATALemergencycontact2relationshipTextField); 
        this.loginFrame = loginFrame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ANTENATALCardPanel = new javax.swing.JPanel();
        ANTENATALpersonallabel = new javax.swing.JLabel();
        ANTENATALKINlabel = new javax.swing.JLabel();
        ANTENATALstateComboBox = new javax.swing.JComboBox();
        ANTENATALmaritalComboBox = new javax.swing.JComboBox();
        ANTENATALreligioncombobox = new javax.swing.JComboBox();
        ANTENATALnationalityComboBox = new javax.swing.JComboBox();
        ANTENATALspouseOccupationTextField = new javax.swing.JTextField();
        ANTENATALspouseAddressTextField = new javax.swing.JTextField();
        ANTENATALemergencycontact1phoneTextField = new javax.swing.JTextField();
        ANTENATALspousephoneTextField = new javax.swing.JTextField();
        ANTENATALCardNoTextField = new javax.swing.JTextField();
        ANTENATALPhoneNumberTextField = new javax.swing.JTextField();
        ANTENATALOccupationTextField = new javax.swing.JTextField();
        ANTENATALAddressTextField = new javax.swing.JTextField();
        ANTENATALSaveButton = new javax.swing.JButton();
        ANTENATALBackToPatOption1Button = new javax.swing.JButton();
        ANTENATALKINlabel1 = new javax.swing.JLabel();
        ANTENATALspouseNameTextField1 = new javax.swing.JTextField();
        ANTENATALemergencycontact1relationshipTextField = new javax.swing.JTextField();
        ANTENATALemergencycontact1nameTextField = new javax.swing.JTextField();
        ANTENATALemergencycontact2nameTextField = new javax.swing.JTextField();
        ANTENATALemergencycontact2phoneTextField = new javax.swing.JTextField();
        ANTENATALemergencycontact2relationshipTextField = new javax.swing.JTextField();
        ANTENATALStartDateChooser = new com.toedter.calendar.JDateChooser();
        ANTENATAspouseLnationalityComboBox1 = new javax.swing.JComboBox();
        ANTENATALspousereligioncombobox1 = new javax.swing.JComboBox();
        ANTENATALAgeTextField = new javax.swing.JTextField();
        ANTENATALlabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 153, 153));
        setPreferredSize(new java.awt.Dimension(836, 623));

        ANTENATALCardPanel.setBackground(new java.awt.Color(102, 153, 255));

        ANTENATALpersonallabel.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        ANTENATALpersonallabel.setText("PERSONAL");

        ANTENATALKINlabel.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        ANTENATALKINlabel.setText("SPOUSE'S DETAILS");

        ANTENATALstateComboBox.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        ANTENATALstateComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select State" }));

        ANTENATALmaritalComboBox.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        ANTENATALmaritalComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Marital Status", "Married", "Single" }));

        ANTENATALreligioncombobox.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        ANTENATALreligioncombobox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Religion", "Christian", "Muslim", "Traditional", "Buddism", "Judaism", "Hinduism", "Others" }));

        ANTENATALnationalityComboBox.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        ANTENATALnationalityComboBox.setMaximumRowCount(100);
        ANTENATALnationalityComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Nationality", "AF  Afghanistan", "AL  Albania", "DZ  Algeria", "AS  American Samoa", "AD  Andorra", "AO  Angola", "AI  Anguilla", "AQ  Antarctica", "AG  Antigua and Barbuda", "AR  Argentina", "AM  Armenia", "AW  Aruba", "AU  Australia", "AT  Austria", "AZ  Azerbaijan", "BS  Bahamas", "BH  Bahrain", "BD  Bangladesh", "BB  Barbados", "BY  Belarus", "BE  Belgium", "BZ  Belize", "BJ  Benin", "BM  Bermuda", "BT  Bhutan", "BO  Bolivia", "BA  Bosnia and Herzegovina", "BW  Botswana", "BV  Bouvet Island", "BR  Brazil", "IO  British Indian Ocean Territory", "VG  British Virgin Islands", "BN  Brunei", "BG  Bulgaria", "BF  Burkina Faso", "BI  Burundi", "KH  Cambodia", "CM  Cameroon", "CA  Canada", "CV  Cape Verde", "KY  Cayman Islands", "CF  Central African Republic", "TD  Chad", "CL  Chile", "CN  China", "CX  Christmas Island", "CC  Cocos Islands", "CO  Colombia", "KM  Comoros", "CG  Congo", "CK  Cook Islands", "CR  Costa Rica", "HR  Croatia", "CU  Cuba", "CY  Cyprus", "CZ  Czech Republic", "CI  Côte d'Ivoire", "DK  Denmark", "DJ  Djibouti", "DM  Dominica", "DO  Dominican Republic", "EC  Ecuador", "EG  Egypt", "SV  El Salvador", "GQ  Equatorial Guinea", "ER  Eritrea", "EE  Estonia", "ET  Ethiopia", "FK  Falkland Islands", "FO  Faroe Islands", "FJ  Fiji", "FI  Finland", "FR  France", "GF  French Guiana", "PF  French Polynesia", "TF  French Southern Territories", "GA  Gabon", "GM  Gambia", "GE  Georgia", "DE  Germany", "GH  Ghana", "GI  Gibraltar", "GR  Greece", "GL  Greenland", "GD  Grenada", "GP  Guadeloupe", "GU  Guam", "GT  Guatemala", "GN  Guinea", "GW  Guinea-Bissau", "GY  Guyana", "HT  Haiti", "HM  Heard Island And McDonald Islands", "HN  Honduras", "HK  Hong Kong", "HU  Hungary", "IS  Iceland", "IN  India", "ID  Indonesia", "IR  Iran", "IQ  Iraq", "IE  Ireland", "IL  Israel", "IT  Italy", "JM  Jamaica", "JP  Japan", "JO  Jordan", "KZ  Kazakhstan", "KE  Kenya", "KI  Kiribati", "KW  Kuwait", "KG  Kyrgyzstan", "LA  Laos", "LV  Latvia", "LB  Lebanon", "LS  Lesotho", "LR  Liberia", "LY  Libya", "LI  Liechtenstein", "LT  Lithuania", "LU  Luxembourg", "MO  Macao", "MK  Macedonia", "MG  Madagascar", "MW  Malawi", "MY  Malaysia", "MV  Maldives", "ML  Mali", "MT  Malta", "MH  Marshall Islands", "MQ  Martinique", "MR  Mauritania", "MU  Mauritius", "YT  Mayotte", "MX  Mexico", "FM  Micronesia", "MD  Moldova", "MC  Monaco", "MN  Mongolia", "ME  Montenegro", "MS  Montserrat", "MA  Morocco", "MZ  Mozambique", "MM  Myanmar", "NA  Namibia", "NR  Nauru", "NP  Nepal", "NL  Netherlands", "AN  Netherlands Antilles", "NC  New Caledonia", "NZ  New Zealand", "NI  Nicaragua", "NE  Niger", "NG  Nigeria", "NU  Niue", "NF  Norfolk Island", "KP  North Korea", "MP  Northern Mariana Islands", "NO  Norway", "OM  Oman", "PK  Pakistan", "PW  Palau", "PS  Palestine", "PA  Panama", "PG  Papua New Guinea", "PY  Paraguay", "PE  Peru", "PH  Philippines", "PN  Pitcairn", "PL  Poland", "PT  Portugal", "PR  Puerto Rico", "QA  Qatar", "RE  Reunion", "RO  Romania", "RU  Russia", "RW  Rwanda", "SH  Saint Helena", "KN  Saint Kitts And Nevis", "LC  Saint Lucia", "PM  Saint Pierre And Miquelon", "VC  Saint Vincent And The Grenadines", "WS  Samoa", "SM  San Marino", "ST  Sao Tome And Principe", "SA  Saudi Arabia", "SN  Senegal", "RS  Serbia", "CS  Serbia and Montenegro", "SC  Seychelles", "SL  Sierra Leone", "SG  Singapore", "SK  Slovakia", "SI  Slovenia", "SB  Solomon Islands", "SO  Somalia", "ZA  South Africa", "GS  South Georgia And The South Sandwich", "Islands KR  South Korea", "ES  Spain", "LK  Sri Lanka", "SD  Sudan", "SR  Suriname", "SJ  Svalbard And Jan Mayen", "SZ  Swaziland", "SE  Sweden", "CH  Switzerland", "SY  Syria", "TW  Taiwan", "TJ  Tajikistan", "TZ  Tanzania", "TH  Thailand", "CD  The Democratic Republic Of Congo", "TL  Timor-Leste", "TG  Togo", "TK  Tokelau", "TO  Tonga", "TT  Trinidad and Tobago", "TN  Tunisia", "TR  Turkey", "TM  Turkmenistan", "TC  Turks And Caicos Islands", "TV  Tuvalu", "VI  U.S. Virgin Islands", "UG  Uganda", "UA  Ukraine", "AE  United Arab Emirates", "GB  United Kingdom", "US  United States", "UM  United States Minor Outlying Islands", "UY  Uruguay", "UZ  Uzbekistan", "VU  Vanuatu", "VA  Vatican", "VE  Venezuela", "VN  Vietnam", "WF  Wallis And Futuna", "EH  Western Sahara", "YE  Yemen", "ZM  Zambia", "ZW  Zimbabwe", "AX  Åland Islands" }));

        ANTENATALspouseOccupationTextField.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N

        ANTENATALspouseAddressTextField.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N

        ANTENATALemergencycontact1phoneTextField.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N

        ANTENATALspousephoneTextField.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N

        ANTENATALCardNoTextField.setFont(new java.awt.Font("Bell MT", 1, 16)); // NOI18N

        ANTENATALPhoneNumberTextField.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N

        ANTENATALOccupationTextField.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N

        ANTENATALAddressTextField.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N

        ANTENATALSaveButton.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        ANTENATALSaveButton.setText("SAVE");
        ANTENATALSaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ANTENATALSaveButtonActionPerformed(evt);
            }
        });

        ANTENATALBackToPatOption1Button.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        ANTENATALBackToPatOption1Button.setText("BACK");
        ANTENATALBackToPatOption1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ANTENATALBackToPatOption1ButtonActionPerformed(evt);
            }
        });

        ANTENATALKINlabel1.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        ANTENATALKINlabel1.setText("IN CASE OF EMERGENCY (contact)");

        ANTENATALspouseNameTextField1.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N

        ANTENATALemergencycontact1relationshipTextField.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N

        ANTENATALemergencycontact1nameTextField.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N

        ANTENATALemergencycontact2nameTextField.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N

        ANTENATALemergencycontact2phoneTextField.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N

        ANTENATALemergencycontact2relationshipTextField.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N

        ANTENATAspouseLnationalityComboBox1.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        ANTENATAspouseLnationalityComboBox1.setMaximumRowCount(100);
        ANTENATAspouseLnationalityComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Spouse's Nationality", "AF  Afghanistan", "AL  Albania", "DZ  Algeria", "AS  American Samoa", "AD  Andorra", "AO  Angola", "AI  Anguilla", "AQ  Antarctica", "AG  Antigua and Barbuda", "AR  Argentina", "AM  Armenia", "AW  Aruba", "AU  Australia", "AT  Austria", "AZ  Azerbaijan", "BS  Bahamas", "BH  Bahrain", "BD  Bangladesh", "BB  Barbados", "BY  Belarus", "BE  Belgium", "BZ  Belize", "BJ  Benin", "BM  Bermuda", "BT  Bhutan", "BO  Bolivia", "BA  Bosnia and Herzegovina", "BW  Botswana", "BV  Bouvet Island", "BR  Brazil", "IO  British Indian Ocean Territory", "VG  British Virgin Islands", "BN  Brunei", "BG  Bulgaria", "BF  Burkina Faso", "BI  Burundi", "KH  Cambodia", "CM  Cameroon", "CA  Canada", "CV  Cape Verde", "KY  Cayman Islands", "CF  Central African Republic", "TD  Chad", "CL  Chile", "CN  China", "CX  Christmas Island", "CC  Cocos Islands", "CO  Colombia", "KM  Comoros", "CG  Congo", "CK  Cook Islands", "CR  Costa Rica", "HR  Croatia", "CU  Cuba", "CY  Cyprus", "CZ  Czech Republic", "CI  Côte d'Ivoire", "DK  Denmark", "DJ  Djibouti", "DM  Dominica", "DO  Dominican Republic", "EC  Ecuador", "EG  Egypt", "SV  El Salvador", "GQ  Equatorial Guinea", "ER  Eritrea", "EE  Estonia", "ET  Ethiopia", "FK  Falkland Islands", "FO  Faroe Islands", "FJ  Fiji", "FI  Finland", "FR  France", "GF  French Guiana", "PF  French Polynesia", "TF  French Southern Territories", "GA  Gabon", "GM  Gambia", "GE  Georgia", "DE  Germany", "GH  Ghana", "GI  Gibraltar", "GR  Greece", "GL  Greenland", "GD  Grenada", "GP  Guadeloupe", "GU  Guam", "GT  Guatemala", "GN  Guinea", "GW  Guinea-Bissau", "GY  Guyana", "HT  Haiti", "HM  Heard Island And McDonald Islands", "HN  Honduras", "HK  Hong Kong", "HU  Hungary", "IS  Iceland", "IN  India", "ID  Indonesia", "IR  Iran", "IQ  Iraq", "IE  Ireland", "IL  Israel", "IT  Italy", "JM  Jamaica", "JP  Japan", "JO  Jordan", "KZ  Kazakhstan", "KE  Kenya", "KI  Kiribati", "KW  Kuwait", "KG  Kyrgyzstan", "LA  Laos", "LV  Latvia", "LB  Lebanon", "LS  Lesotho", "LR  Liberia", "LY  Libya", "LI  Liechtenstein", "LT  Lithuania", "LU  Luxembourg", "MO  Macao", "MK  Macedonia", "MG  Madagascar", "MW  Malawi", "MY  Malaysia", "MV  Maldives", "ML  Mali", "MT  Malta", "MH  Marshall Islands", "MQ  Martinique", "MR  Mauritania", "MU  Mauritius", "YT  Mayotte", "MX  Mexico", "FM  Micronesia", "MD  Moldova", "MC  Monaco", "MN  Mongolia", "ME  Montenegro", "MS  Montserrat", "MA  Morocco", "MZ  Mozambique", "MM  Myanmar", "NA  Namibia", "NR  Nauru", "NP  Nepal", "NL  Netherlands", "AN  Netherlands Antilles", "NC  New Caledonia", "NZ  New Zealand", "NI  Nicaragua", "NE  Niger", "NG  Nigeria", "NU  Niue", "NF  Norfolk Island", "KP  North Korea", "MP  Northern Mariana Islands", "NO  Norway", "OM  Oman", "PK  Pakistan", "PW  Palau", "PS  Palestine", "PA  Panama", "PG  Papua New Guinea", "PY  Paraguay", "PE  Peru", "PH  Philippines", "PN  Pitcairn", "PL  Poland", "PT  Portugal", "PR  Puerto Rico", "QA  Qatar", "RE  Reunion", "RO  Romania", "RU  Russia", "RW  Rwanda", "SH  Saint Helena", "KN  Saint Kitts And Nevis", "LC  Saint Lucia", "PM  Saint Pierre And Miquelon", "VC  Saint Vincent And The Grenadines", "WS  Samoa", "SM  San Marino", "ST  Sao Tome And Principe", "SA  Saudi Arabia", "SN  Senegal", "RS  Serbia", "CS  Serbia and Montenegro", "SC  Seychelles", "SL  Sierra Leone", "SG  Singapore", "SK  Slovakia", "SI  Slovenia", "SB  Solomon Islands", "SO  Somalia", "ZA  South Africa", "GS  South Georgia And The South Sandwich", "Islands KR  South Korea", "ES  Spain", "LK  Sri Lanka", "SD  Sudan", "SR  Suriname", "SJ  Svalbard And Jan Mayen", "SZ  Swaziland", "SE  Sweden", "CH  Switzerland", "SY  Syria", "TW  Taiwan", "TJ  Tajikistan", "TZ  Tanzania", "TH  Thailand", "CD  The Democratic Republic Of Congo", "TL  Timor-Leste", "TG  Togo", "TK  Tokelau", "TO  Tonga", "TT  Trinidad and Tobago", "TN  Tunisia", "TR  Turkey", "TM  Turkmenistan", "TC  Turks And Caicos Islands", "TV  Tuvalu", "VI  U.S. Virgin Islands", "UG  Uganda", "UA  Ukraine", "AE  United Arab Emirates", "GB  United Kingdom", "US  United States", "UM  United States Minor Outlying Islands", "UY  Uruguay", "UZ  Uzbekistan", "VU  Vanuatu", "VA  Vatican", "VE  Venezuela", "VN  Vietnam", "WF  Wallis And Futuna", "EH  Western Sahara", "YE  Yemen", "ZM  Zambia", "ZW  Zimbabwe", "AX  Åland Islands" }));

        ANTENATALspousereligioncombobox1.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        ANTENATALspousereligioncombobox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Spouse's Religion", "Christian", "Muslim", "Traditional", "Buddism", "Judaism", "Hinduism", "Others" }));

        ANTENATALAgeTextField.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N

        javax.swing.GroupLayout ANTENATALCardPanelLayout = new javax.swing.GroupLayout(ANTENATALCardPanel);
        ANTENATALCardPanel.setLayout(ANTENATALCardPanelLayout);
        ANTENATALCardPanelLayout.setHorizontalGroup(
            ANTENATALCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ANTENATALCardPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(ANTENATALCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ANTENATALCardPanelLayout.createSequentialGroup()
                        .addGroup(ANTENATALCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ANTENATALpersonallabel)
                            .addGroup(ANTENATALCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(ANTENATALAddressTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ANTENATALstateComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ANTENATALCardPanelLayout.createSequentialGroup()
                                    .addGroup(ANTENATALCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(ANTENATALOccupationTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                                        .addComponent(ANTENATALreligioncombobox, 0, 320, Short.MAX_VALUE)
                                        .addComponent(ANTENATALStartDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(28, 28, 28)
                                    .addGroup(ANTENATALCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(ANTENATALnationalityComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ANTENATALmaritalComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ANTENATALAgeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(ANTENATALCardPanelLayout.createSequentialGroup()
                                    .addGroup(ANTENATALCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(ANTENATALspouseOccupationTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(ANTENATALspouseNameTextField1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                                    .addGroup(ANTENATALCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(ANTENATALspousephoneTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                                        .addComponent(ANTENATALspousereligioncombobox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addComponent(ANTENATALKINlabel))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(ANTENATALCardPanelLayout.createSequentialGroup()
                        .addComponent(ANTENATALCardNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(ANTENATALPhoneNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(27, Short.MAX_VALUE))))
            .addGroup(ANTENATALCardPanelLayout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addComponent(ANTENATALBackToPatOption1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addComponent(ANTENATALSaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(ANTENATALCardPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(ANTENATALCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ANTENATALCardPanelLayout.createSequentialGroup()
                        .addComponent(ANTENATALKINlabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ANTENATALCardPanelLayout.createSequentialGroup()
                        .addGroup(ANTENATALCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(ANTENATALCardPanelLayout.createSequentialGroup()
                                .addComponent(ANTENATAspouseLnationalityComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ANTENATALspouseAddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ANTENATALCardPanelLayout.createSequentialGroup()
                                .addGroup(ANTENATALCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ANTENATALemergencycontact2nameTextField)
                                    .addComponent(ANTENATALemergencycontact1nameTextField))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(ANTENATALCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ANTENATALemergencycontact2phoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ANTENATALemergencycontact1phoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(ANTENATALCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ANTENATALemergencycontact1relationshipTextField)
                                    .addComponent(ANTENATALemergencycontact2relationshipTextField))))
                        .addGap(28, 28, 28))))
        );
        ANTENATALCardPanelLayout.setVerticalGroup(
            ANTENATALCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ANTENATALCardPanelLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(ANTENATALpersonallabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ANTENATALCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ANTENATALPhoneNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ANTENATALCardNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ANTENATALCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ANTENATALOccupationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ANTENATALAgeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ANTENATALCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ANTENATALmaritalComboBox, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(ANTENATALStartDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ANTENATALCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ANTENATALreligioncombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ANTENATALnationalityComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ANTENATALstateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ANTENATALAddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ANTENATALKINlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ANTENATALCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ANTENATALCardPanelLayout.createSequentialGroup()
                        .addGroup(ANTENATALCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ANTENATALspousephoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ANTENATALspouseNameTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ANTENATALspouseOccupationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ANTENATALspousereligioncombobox1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ANTENATALCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ANTENATAspouseLnationalityComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ANTENATALspouseAddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(ANTENATALKINlabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ANTENATALCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ANTENATALemergencycontact1nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ANTENATALemergencycontact1phoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ANTENATALemergencycontact1relationshipTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ANTENATALCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ANTENATALemergencycontact2nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ANTENATALemergencycontact2phoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ANTENATALemergencycontact2relationshipTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ANTENATALCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ANTENATALBackToPatOption1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ANTENATALSaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        ANTENATALlabel.setFont(new java.awt.Font("Bell MT", 1, 20)); // NOI18N
        ANTENATALlabel.setText("POST/ANTE-NATAL ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ANTENATALlabel)
                    .addComponent(ANTENATALCardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(ANTENATALlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ANTENATALCardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
 private void textCustomise(String text, JTextField component)
    {
        PromptSupport.setPrompt(text, component);
        PromptSupport.setFocusBehavior(PromptSupport.FocusBehavior.HIDE_PROMPT, component);
        PromptSupport.setFocusBehavior(PromptSupport.FocusBehavior.SHOW_PROMPT, component);
        PromptSupport.setFontStyle(Font.BOLD, component);
        PromptSupport.setForeground(Color.darkGray, component);
    }
    
    private void ANTENATALBackToPatOption1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ANTENATALBackToPatOption1ButtonActionPerformed
        // TODO add your handling code here:
        JPanel optPanel = loginFrame.getPatOptionPanell();
        loginFrame.updatePanel(optPanel);
    }//GEN-LAST:event_ANTENATALBackToPatOption1ButtonActionPerformed

    private void ANTENATALSaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ANTENATALSaveButtonActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat sFormat = new SimpleDateFormat("yyyy-MM-dd");
       
        String cardNo = ANTENATALCardNoTextField.getText();
        String phone = ANTENATALPhoneNumberTextField.getText();
        String occupation = ANTENATALOccupationTextField.getText();
        String addr = ANTENATALAddressTextField.getText();
        
        String mStatus = (String) ANTENATALmaritalComboBox.getSelectedItem();
        String religion = (String) ANTENATALreligioncombobox.getSelectedItem();
        String nationality = (String)ANTENATALnationalityComboBox.getSelectedItem();
        String state = (String)ANTENATALstateComboBox.getSelectedItem();
        String spouseName = ANTENATALspouseNameTextField1.getText();
        String spouseAddr = ANTENATALspouseAddressTextField.getText();
        String spousePhone = ANTENATALspousephoneTextField.getText();
        String spouseOccu = ANTENATALspouseOccupationTextField.getText();
        String spousereligion = (String) ANTENATALspousereligioncombobox1.getSelectedItem();
        String spousenationality = (String)ANTENATAspouseLnationalityComboBox1.getSelectedItem();       
        String contact1Name = ANTENATALemergencycontact1nameTextField.getText();
        String contact1phone = ANTENATALemergencycontact1phoneTextField.getText();
        String contact1relation = ANTENATALemergencycontact1relationshipTextField.getText();
        String contact2Name = ANTENATALemergencycontact2nameTextField.getText();
        String contact2phone = ANTENATALemergencycontact2phoneTextField.getText();
        String contact2relation = ANTENATALemergencycontact2relationshipTextField.getText();
        if (!validated(cardNo, phone,occupation, addr,mStatus, religion, nationality, state, spouseName, spouseAddr, spousePhone, spouseOccu, spousereligion, spousenationality, contact1Name, contact1phone, contact1relation, contact2Name, contact2phone, contact2relation))
                {
            JOptionPane.showMessageDialog(loginFrame, "Fill in all Spaces");
                }
        else
        {
            Date dateOfstart = ANTENATALStartDateChooser.getDate();
            String dateOfRegstart = sFormat.format(dateOfstart);
            int age = Integer.parseInt(ANTENATALAgeTextField.getText());
            
            DBoperations db = new DBoperations();
        db.ANTENATALcardsave (cardNo, phone, addr, occupation, dateOfRegstart, mStatus, age, religion, nationality, state, spouseName, spouseAddr, 
             spousePhone, spouseOccu,spousenationality,spousereligion,contact1Name,contact1phone,contact1relation,contact2Name,contact2phone,contact2relation);
        
        ANTENATALCardNoTextField.setText("");
        ANTENATALPhoneNumberTextField.setText("");
        ANTENATALOccupationTextField.setText("");
        ANTENATALAddressTextField.setText("");
        ANTENATALStartDateChooser.setDate(null);
        ANTENATALAgeTextField.setText("");
        ANTENATALmaritalComboBox.setSelectedItem("Marital Status");
        ANTENATALreligioncombobox.setSelectedItem("Select Religion");
        ANTENATALnationalityComboBox.setSelectedItem("Select Nationality");
        ANTENATALstateComboBox.setSelectedItem("Select State");
        ANTENATALspouseNameTextField1.setText("");
        ANTENATALspouseAddressTextField.setText("");
        ANTENATALspousephoneTextField.setText("");
        ANTENATALspouseOccupationTextField.setText("");
        ANTENATALspousereligioncombobox1.setSelectedItem(null);
        ANTENATAspouseLnationalityComboBox1.setSelectedItem(null);
        ANTENATALemergencycontact1nameTextField.setText("");
        ANTENATALemergencycontact1phoneTextField.setText("");
        ANTENATALemergencycontact1relationshipTextField.setText("");
        ANTENATALemergencycontact2nameTextField.setText("");
        ANTENATALemergencycontact2phoneTextField.setText("");
        ANTENATALemergencycontact2relationshipTextField.setText(""); 
       }
    }//GEN-LAST:event_ANTENATALSaveButtonActionPerformed

private boolean 
validated(String cardNo,String phone, String occupation ,String addr ,String mStatus,String religion, 
String nationality, String state ,String spouseName, String spouseAddr, String spousePhone,String spouseOccu ,String spousereligion,
String spousenationality,String contact1Name,String contact1phone, String contact1relation, String contact2Name,String contact2phone,String contact2relation)
  {
    if(cardNo.isEmpty() || phone.isEmpty()||occupation.isEmpty() || addr.isEmpty()||mStatus.isEmpty()||religion.isEmpty() || nationality.isEmpty()||
       state.isEmpty() || spouseName.isEmpty()||spouseAddr.isEmpty() || spouseOccu.isEmpty()||spousePhone.isEmpty()||spousenationality.isEmpty()||spousereligion.isEmpty() || contact1Name.isEmpty()||contact1phone.isEmpty()||contact1relation.isEmpty()||
       contact2Name.isEmpty()||contact2phone.isEmpty()||contact2relation.isEmpty())
    {
        return false;
    }
    return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ANTENATALAddressTextField;
    private javax.swing.JTextField ANTENATALAgeTextField;
    private javax.swing.JButton ANTENATALBackToPatOption1Button;
    private javax.swing.JTextField ANTENATALCardNoTextField;
    private javax.swing.JPanel ANTENATALCardPanel;
    private javax.swing.JLabel ANTENATALKINlabel;
    private javax.swing.JLabel ANTENATALKINlabel1;
    private javax.swing.JTextField ANTENATALOccupationTextField;
    private javax.swing.JTextField ANTENATALPhoneNumberTextField;
    private javax.swing.JButton ANTENATALSaveButton;
    private com.toedter.calendar.JDateChooser ANTENATALStartDateChooser;
    private javax.swing.JTextField ANTENATALemergencycontact1nameTextField;
    private javax.swing.JTextField ANTENATALemergencycontact1phoneTextField;
    private javax.swing.JTextField ANTENATALemergencycontact1relationshipTextField;
    private javax.swing.JTextField ANTENATALemergencycontact2nameTextField;
    private javax.swing.JTextField ANTENATALemergencycontact2phoneTextField;
    private javax.swing.JTextField ANTENATALemergencycontact2relationshipTextField;
    private javax.swing.JLabel ANTENATALlabel;
    private javax.swing.JComboBox ANTENATALmaritalComboBox;
    private javax.swing.JComboBox ANTENATALnationalityComboBox;
    private javax.swing.JLabel ANTENATALpersonallabel;
    private javax.swing.JComboBox ANTENATALreligioncombobox;
    private javax.swing.JTextField ANTENATALspouseAddressTextField;
    private javax.swing.JTextField ANTENATALspouseNameTextField1;
    private javax.swing.JTextField ANTENATALspouseOccupationTextField;
    private javax.swing.JTextField ANTENATALspousephoneTextField;
    private javax.swing.JComboBox ANTENATALspousereligioncombobox1;
    private javax.swing.JComboBox ANTENATALstateComboBox;
    private javax.swing.JComboBox ANTENATAspouseLnationalityComboBox1;
    // End of variables declaration//GEN-END:variables
}
