/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.health.hospital;

import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author chinex
 */
public class SignupForm extends javax.swing.JFrame {
    /**
     * Creates new form SignupForm
     */
    private Connection con;
    private PreparedStatement pt;
    private ResultSet st;
    private String userDb = "root";
    private String passwordDb = "";
    private String urlDb = "jdbc:mysql://localhost:3306/form_db";
    
    public SignupForm() {
        initComponents();
   
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        createAcct = new javax.swing.JLabel();
        frontPanel = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        firstTextField = new javax.swing.JTextField();
        roleComboBox1 = new javax.swing.JComboBox();
        lastname = new javax.swing.JLabel();
        confirmpassword = new javax.swing.JLabel();
        gender = new javax.swing.JLabel();
        age = new javax.swing.JLabel();
        ageTextField = new javax.swing.JTextField();
        usernameTextField = new javax.swing.JTextField();
        LastnameTextField1 = new javax.swing.JTextField();
        role = new javax.swing.JLabel();
        firstname = new javax.swing.JLabel();
        femaleRadioButton = new javax.swing.JRadioButton();
        maleRadioButton = new javax.swing.JRadioButton();
        username = new javax.swing.JLabel();
        registerButton1 = new javax.swing.JButton();
        jCONFIRMPasswordField = new javax.swing.JPasswordField();
        password = new javax.swing.JLabel();
        jPasswordField = new javax.swing.JPasswordField();
        SIDEPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("BEUHIER HOSPITAL MANAGEMENT SYSTEM ");
        setBackground(new java.awt.Color(153, 153, 153));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        createAcct.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        createAcct.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        createAcct.setText("CREATE YOUR ACCOUNT");

        frontPanel.setBackground(new java.awt.Color(153, 153, 255));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setPreferredSize(new java.awt.Dimension(50, 50));

        firstTextField.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N

        roleComboBox1.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        roleComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "select Role", "Doctor", "Nurse" }));

        lastname.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        lastname.setText("LASTNAME");

        confirmpassword.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        confirmpassword.setText("CONFIRM PASSWORD");

        gender.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        gender.setText("GENDER");

        age.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        age.setText("AGE");

        ageTextField.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        ageTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ageTextFieldKeyReleased(evt);
            }
        });

        usernameTextField.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N

        LastnameTextField1.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N

        role.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        role.setText("ROLE");

        firstname.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        firstname.setText("FIRSTNAME");

        femaleRadioButton.setBackground(new java.awt.Color(153, 153, 255));
        buttonGroup1.add(femaleRadioButton);
        femaleRadioButton.setFont(new java.awt.Font("Bell MT", 3, 11)); // NOI18N
        femaleRadioButton.setText("FEMALE");

        maleRadioButton.setBackground(new java.awt.Color(153, 153, 255));
        buttonGroup1.add(maleRadioButton);
        maleRadioButton.setFont(new java.awt.Font("Bell MT", 3, 11)); // NOI18N
        maleRadioButton.setText("MALE");

        username.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        username.setText("USERNAME");

        registerButton1.setBackground(new java.awt.Color(153, 153, 153));
        registerButton1.setFont(new java.awt.Font("Bell MT", 3, 24)); // NOI18N
        registerButton1.setText("REGISTER");
        registerButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButton1ActionPerformed(evt);
            }
        });

        jCONFIRMPasswordField.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N

        password.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        password.setText("PASSWORD");

        jPasswordField.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N

        javax.swing.GroupLayout frontPanelLayout = new javax.swing.GroupLayout(frontPanel);
        frontPanel.setLayout(frontPanelLayout);
        frontPanelLayout.setHorizontalGroup(
            frontPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frontPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(frontPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(gender)
                    .addComponent(ageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LastnameTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastname)
                    .addComponent(firstTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstname)
                    .addGroup(frontPanelLayout.createSequentialGroup()
                        .addComponent(maleRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(femaleRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(48, 48, 48)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(frontPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frontPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(registerButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98))
                    .addGroup(frontPanelLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(frontPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(role)
                            .addComponent(confirmpassword)
                            .addComponent(jCONFIRMPasswordField)
                            .addComponent(jPasswordField)
                            .addComponent(password)
                            .addComponent(username)
                            .addComponent(usernameTextField)
                            .addComponent(roleComboBox1, 0, 304, Short.MAX_VALUE))
                        .addContainerGap(44, Short.MAX_VALUE))))
        );
        frontPanelLayout.setVerticalGroup(
            frontPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frontPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(frontPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frontPanelLayout.createSequentialGroup()
                        .addComponent(firstname, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(firstTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(lastname, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frontPanelLayout.createSequentialGroup()
                        .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)))
                .addGroup(frontPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frontPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(confirmpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jCONFIRMPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(role, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(roleComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                        .addComponent(registerButton1)
                        .addGap(43, 43, 43))
                    .addGroup(frontPanelLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(LastnameTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addGroup(frontPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(femaleRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                            .addComponent(maleRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        SIDEPanel.setBackground(new java.awt.Color(51, 153, 255));

        javax.swing.GroupLayout SIDEPanelLayout = new javax.swing.GroupLayout(SIDEPanel);
        SIDEPanel.setLayout(SIDEPanelLayout);
        SIDEPanelLayout.setHorizontalGroup(
            SIDEPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        SIDEPanelLayout.setVerticalGroup(
            SIDEPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(frontPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(createAcct, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SIDEPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(createAcct, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(frontPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(SIDEPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        LoginFrame LF = new LoginFrame ();
        LF.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void registerButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButton1ActionPerformed
        // TODO add your handling code here:
try 
{
        String fn = firstTextField.getText();
        String ln = LastnameTextField1.getText();
        String un = usernameTextField.getText();
        String pwd = jPasswordField.getText();
        String cpwd = jCONFIRMPasswordField.getText();
        int ag = Integer.parseInt(ageTextField.getText());
        String role = roleComboBox1.getSelectedItem().toString();
        
        String gender;
        if (maleRadioButton.isSelected())
        {
           gender = "male"; 
        }
        else 
        {
           gender = "female";
        }
        
        if (!pwd.equals(cpwd))
        {
            //Display
            jCONFIRMPasswordField.setText("");
            JOptionPane.showMessageDialog(rootPane, "Password Mismatch");
        }
        else
        {
            //proceed
             if (fn.isEmpty() || ln.isEmpty() || un.isEmpty() || role.equalsIgnoreCase("select Role"))
            {
                JOptionPane.showMessageDialog(rootPane, "Please Complete the form");  
            }
             else
            {           
            String query = "INSERT INTO staff_tb (username,age, password, firstname, lastname, gender, role) VALUE(?, ?, ?, ?, ?, ?, ?)";
                    
                    con = DriverManager.getConnection(urlDb, userDb, passwordDb);
                    pt = con.prepareStatement(query);
                    
                    pt.setString(1, un);
                     pt.setInt(2, ag);
                    pt.setString(3, pwd);
                    pt.setString(4, fn);
                    pt.setString(5, ln);
                    pt.setString(6, gender);
                    pt.setString(7, role);
                   
                    
                    int row = pt.executeUpdate();
                    
                    if(row>0)
                    {
                        JOptionPane.showMessageDialog(this, "Registration Successful");
                    }                    
            }            
        }     
    }//GEN-LAST:event_registerButton1ActionPerformed
catch(NumberFormatException ex)
{
    ex.printStackTrace();
 JOptionPane.showMessageDialog(rootPane, "Please Enter a valid Age");
}       catch (SQLException ex) {
            Logger.getLogger(SignupForm.class.getName()).log(Level.SEVERE, null, ex);
        }
finally{
            try 
            {
                if(pt!=null)
                {
                    pt.close();
                }
                if(con!=null)
                {
                    con.close();
                }
            } 
            catch (SQLException ex) 
            {
                    Logger.getLogger(SignupForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        firstTextField.setText("");
        LastnameTextField1.setText("");
        usernameTextField.setText("");
        jPasswordField.setText("");
        jCONFIRMPasswordField.setText("");
        ageTextField.setText("");
        roleComboBox1.setSelectedItem("Select Role");
    }
    private void ageTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ageTextFieldKeyReleased
        // TODO add your handling code here:
        //String ag = age.getText();
        //if ()
    }//GEN-LAST:event_ageTextFieldKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignupForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignupForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignupForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignupForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignupForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField LastnameTextField1;
    private javax.swing.JPanel SIDEPanel;
    private javax.swing.JLabel age;
    private javax.swing.JTextField ageTextField;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel confirmpassword;
    private javax.swing.JLabel createAcct;
    private javax.swing.JRadioButton femaleRadioButton;
    private javax.swing.JTextField firstTextField;
    private javax.swing.JLabel firstname;
    private javax.swing.JPanel frontPanel;
    private javax.swing.JLabel gender;
    private javax.swing.JPasswordField jCONFIRMPasswordField;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lastname;
    private javax.swing.JRadioButton maleRadioButton;
    private javax.swing.JLabel password;
    private javax.swing.JButton registerButton1;
    private javax.swing.JLabel role;
    private javax.swing.JComboBox roleComboBox1;
    private javax.swing.JLabel username;
    private javax.swing.JTextField usernameTextField;
    // End of variables declaration//GEN-END:variables
}
