/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.health.hospital;

import java.util.HashMap;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author chinex
 */
public class TabularcardRecordPanel extends javax.swing.JPanel {

    /**
     * Creates new form TabularcardRecordPanel
     */
    
    HashMap<String, String[]> objMap;
    private String cardNo;
    public TabularcardRecordPanel(HashMap<String, String[]> objMap, String cardNo) {
        initComponents();
        
        this.objMap = objMap;
        
        populateTable(this.objMap);
       
       tablecardNoLabel.setText(" Card Number: " + cardNo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        cardRecordTable = new javax.swing.JTable();
        tablecardNoLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 102, 102));
        setPreferredSize(new java.awt.Dimension(836, 623));

        cardRecordTable.setFont(new java.awt.Font("Bell MT", 1, 15)); // NOI18N
        cardRecordTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Full Name", "Start Date", "End Date", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(cardRecordTable);

        tablecardNoLabel.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        tablecardNoLabel.setText("Card No.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 776, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tablecardNoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tablecardNoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(107, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents


    private void populateTable(HashMap<String, String[]> obj)
    {
        DefaultTableModel DTM = (DefaultTableModel) cardRecordTable.getModel();
        for (int i=0; i<obj.size(); i++)
        {
         
         String data []  = obj.get(String.valueOf(i));
         
         DTM.addRow(data);
         cardRecordTable.setRowHeight(i, 25);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable cardRecordTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel tablecardNoLabel;
    // End of variables declaration//GEN-END:variables
}
